language: rust
cache: cargo
addons:
  apt:
    packages:
      - libssl-dev
      - libssh-dev
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
- cargo clean
- cargo build
- cargo test
