language: rust
dist: trusty
sudo: required
cache: cargo
addons:
  apt:
    packages:
    - libssl-dev
env:
  global:
    - CRATE_NAME=cargo-tarpaulin
rust:
  - 1.27.1
  - 1.27.2
  - 1.28.0
script:
  - cargo clean
  - RUST_BACKTRACE=1 cargo build
  - cargo test
before_deploy:
  - sh ci/before_deploy2.sh
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_RUST_VERSION-$TRAVIS_TAG-travis.*
  skip_cleanup: true
  on:
    tags: true
