language: rust
dist: trusty
sudo: required
cache: cargo
addons:
  apt:
    packages:
      - libssl-dev
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
- cargo clean
- RUST_BACKTRRACE=1 cargo build
- cargo test

branches:
  only:
    - master
