[package]
name = "cargo-tarpaulin"
version = "0.5.7"
authors = ["Daniel McKenna <danielmckenna93@gmail.com>"]
description = "Cargo-Tarpaulin is a tool to determine code coverage achieved via tests"
repository = "https://github.com/xd009642/tarpaulin"
readme = "README.md"
license = "MIT/Apache-2.0"
categories = ["development-tools"]
keywords = ["cargo", "cargo-subcommand", "testing"]

[[bin]]
name = "cargo-tarpaulin"

[dependencies]
nix = "0.10.0"
libc = "0.2.40"
gimli = "0.15.0"
fallible-iterator = "0.1.4"
memmap = "0.6.2"
object = "0.8"
rustc-demangle = "0.1.7"
cargo = "0.24"
clap = "2.31.2"
serde = "1.0.57"
serde_json = "1.0.17"
coveralls-api = "0.3.3"
quick-xml = "0.12.1"
regex = "1.0.0"
lazy_static = "1.0"
syn = { version = "0.14.0", features = ["full"]}
proc-macro2 = "0.4.3"
walkdir = "2"
