[package]
name = "cargo-tarpaulin"
version = "0.3.11"
authors = ["Daniel McKenna <danielmckenna93@gmail.com>"]
description = "Cargo-Tarpaulin is a tool to determine code coverage achieved via tests"
repository = "https://github.com/xd009642/tarpaulin"
readme = "README.md"
license = "MIT/Apache-2.0"
categories = ["development-tools"]
keywords = ["cargo", "cargo-subcommand", "testing"]

[[bin]]
name = "cargo-tarpaulin"

[dependencies]
nix = "0.8.0"
libc = "0.2"
gimli = "0.13.0"
fallible-iterator = "0.1.3"
memmap = "0.5.2"
object = "0.3.0"
rustc-demangle = "0.1.4"
cargo = "0.18.0"
regex = "0.2.1"
clap = "2"
serde = "1.0.2"
serde_json = "1.0.2"
coveralls-api = "0.3.3"
