[package]
name = "cargo-tarpaulin"
version = "0.1.0"
authors = ["Daniel McKenna <danielmckenna93@gmail.com>"]
license = "MIT/Apache-2.0"
categories = ["development-tools"]
keywords = ["cargo", "cargo-subcommand", "testing"]

[[bin]]
name = "cargo-tarpaulin"

[dependencies]
docopt = "0.7.*"
rustc-serialize = "0.3"
nix = "0.8.0"
libc = "0.2"
gimli = "0.13.0"
fallible-iterator = "0.1.3"
memmap = "0.5.2"
object = "0.3.0"
rustc-demangle = "0.1.4"
cargo = "0.18.0"
regex = "0.2.1"
